# Generated by Django 5.1.4 on 2025-06-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_musician_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('profession', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
 