# Generated by Django 5.1.4 on 2025-06-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_service_description_alter_service_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='rate',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')]),
        ),
    ]
